# https://zensical.org/docs/publish-your-site/#with-github-actions
name: docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - .github/workflows/docs.yml
      - mkdocs.yml
      - requirements/requirements-docs.txt
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  container:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v7
        with:
          # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-systems-like-github-actions
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.14.0"
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build docs
        run: uv run zensical build --clean 
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - name: Deploy site
        uses: actions/deploy-pages@v5
        id: deployment
